<?php


namespace App\Presenters\AdminModule;

use App\Forms\Admin\Vote\EditForm;
use App\Forms\Admin\Vote\CreateForm;
use App\Model\DynamicRepository;
use App\Model\Security\Auth\Authenticator;
use App\Presenters\AdminBasePresenter;

use Nette\Application\AbortException;
use Nette\Application\UI\Multiplier;
use Nette\Database\Context;
use Nette\Application\UI\Form;

/**
 * Class VotePresenter
 * @package App\Presenters\AdminModule
 */
class VotePresenter extends AdminBasePresenter
{
    private DynamicRepository $voteRepository;

    /**
     * VotePresenter constructor.
     * @param Authenticator $authenticator
     * @param Context $context
     */
    public function __construct(Authenticator $authenticator, Context $context)
    {
        parent::__construct($authenticator);

        $this->voteRepository = new DynamicRepository($context, 'vote');
    }

    public function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub
    }

    public function renderList() {
        $this->template->votePlatforms = $this->voteRepository->findAll();
    }

    /**
     * @param $id
     */
    public function renderEdit($id) {
        $this->template->voteId = $id;
    }

    /**
     * @param $id
     * @throws AbortException
     */
    public function actionDelete($id) {
        $deleted = $this->voteRepository->delete("id = ?", $id);
        if($deleted) {
            $this->flashMessage('Služba byla úspěšně odstraněna!', 'success');
        } else {
            $this->flashMessage('Tato služba neexistovala, tudíž nemohla být odstraněna.', 'danger');
        }
        $this->redirect('Vote:list');
    }

    /**
     * @return Form
     */
    public function createComponentCreateForm(): Form {
        return (new CreateForm($this->voteRepository, $this))->create();
    }

    public function createComponentEditForm(): Multiplier {
        return new Multiplier(function(string $id) {
            return (new EditForm($this->voteRepository, $this, $id))->create();
        });
    }
}