<?php

namespace App\Presenters\PanelModule;

use App\Forms\Panel\SignInForm;
use App\Model\Security\Auth\PluginAuthenticator;
use App\Model\Security\Exceptions\AuthException;
use App\Model\SettingsRepository;
use App\Presenters\PanelBasePresenter;

use Nette\Application\AbortException;
use Nette\Application\UI\Form;

class LoginPresenter extends PanelBasePresenter
{
    private PluginAuthenticator $pluginAuthenticator;
    private SettingsRepository $settingsRepository;

    /**
     * LoginPresenter constructor.
     * @param PluginAuthenticator $pluginAuthenticator
     * @param SettingsRepository $settingsRepository
     */
    public function __construct(PluginAuthenticator $pluginAuthenticator, SettingsRepository $settingsRepository)
    {
        parent::__construct($settingsRepository);

        $this->pluginAuthenticator = $pluginAuthenticator;
        $this->settingsRepository = $settingsRepository;
    }

    public function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub
    }

    /**
     * @throws AbortException
     */
    public function renderMain() {
        if((bool)$this->pluginAuthenticator->getUser()) {
            $this->redirect('Main:home');
        }
    }

    /**
     * @throws AbortException
     */
    public function actionLogout() {
        try {
            $this->pluginAuthenticator->logout();
            $this->flashMessage('Byl jsi odhlášen, pro další manipulaci s panelem se přihlaš!', 'dark-green');
            $this->redirect('Login:main');
        } catch (AuthException $e) {
            $this->flashMessage($e->getMessage(), 'error');
        }
    }

    public function createComponentSignInForm(): Form {
        return (new SignInForm($this->pluginAuthenticator, $this))->create();
    }
}