<?php


namespace App\Presenters;


use App\Model\Security\Auth\Authenticator;

use Nette\Application\AbortException;

/**
 * Class AdminBasePresenter
 * @package App\Presenters
 */
class AdminBasePresenter extends BasePresenter
{
    private Authenticator $authenticator;
    protected array $admin;

    /**
     * AdminBasePresenter constructor.
     * @param Authenticator $authenticator
     */
    public function __construct(Authenticator $authenticator)
    {
        parent::__construct();

        $this->authenticator = $authenticator;
    }

    /**
     * @throws AbortException
     */
    public function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub
        $user = $this->authenticator->getUser();
        if(!(bool)$user) {
            $this->flashMessage('Pro manipulaci s administrací, proveďte autorizaci.', 'danger');
            $this->redirect(':Front:Login:main');
        } else {
            $this->admin = [
                'name' => $user->name,
                'email' => $user->email,
                'id' => $user->id,
            ];
            $this->template->admin = $this->admin;
        }
    }
}