<?php

namespace App\Presenters;

use App\Model\DI\GoogleAnalytics;
use App\Model\Utils;
use Nette;
use Contributte;
use Nette\Application\Helpers;

/**
 * Class BasePresenter
 * @package App\Presenters
 */
abstract class BasePresenter extends Nette\Application\UI\Presenter
{
    private GoogleAnalytics $googleAnalytics;

    /** @var Nette\Localization\Translator @inject */
    public Nette\Localization\Translator $translator;

    /** @var Contributte\Translation\LocalesResolvers\Session @inject */
    public Contributte\Translation\LocalesResolvers\Session $translatorSessionResolver;

    /**
     * BasePresenter constructor.
     * @param GoogleAnalytics $googleAnalytics
     */
    public function __construct(GoogleAnalytics $googleAnalytics)
    {
        parent::__construct();

        $this->googleAnalytics = $googleAnalytics;
    }

    /**
     * @return array
     */
    public function formatTemplateFiles(): array
    {
        [$module, $presenter] = Helpers::splitName($this->getName());
        $dir = dirname(static::getReflection()->getFileName());
        $dir = is_dir("$dir/templates") ? $dir : dirname($dir);
        return [
            "$dir/templates/$module/$presenter/$this->view.latte",
            "$dir/templates/$module/$presenter.$this->view.latte",
        ];
    }

    public function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub

        $this->template->sklonovani = fn($pocet, $slova) => Utils::sklonovani($pocet, $slova);
        $this->template->httpRequest = $this->getHttpRequest();
        $this->template->googleAnalytics = $this->googleAnalytics;
    }
}