<?php

namespace App\Presenters\HelpDeskModule;

use App\Forms\Panel\Tickets\AddResponseForm;
use App\Forms\Panel\Tickets\CloseTicketForm;
use App\Forms\Panel\Tickets\OpenTicketForm;
use App\Model\DI\GoogleAnalytics;
use App\Model\Panel\Core\Tickets\TicketRepository;
use App\Model\Security\Auth\SupportAuthenticator;
use App\Model\Security\Exceptions\AuthException;
use App\Model\SettingsRepository;
use App\Presenters\HelpBasePresenter;
use Nette\Application\AbortException;
use App\Model\Security\Form\Captcha;
use Nette\Application\UI\Multiplier;
use Nette\Database\Table\ActiveRow;
use Tracy\Debugger;

/**
 * Class MainPresenter
 * @package App\Presenters\HelpDeskModule
 */
class MainPresenter extends HelpBasePresenter
{
    private SupportAuthenticator $supportAuthenticator;
    private TicketRepository $ticketRepository;

    private ActiveRow $user;

    /**
     * MainPresenter constructor.
     * @param SupportAuthenticator $supportAuthenticator
     * @param SettingsRepository $settingsRepository
     * @param TicketRepository $ticketRepository
     */
    public function __construct(SupportAuthenticator $supportAuthenticator, SettingsRepository $settingsRepository, TicketRepository $ticketRepository)
    {
        parent::__construct($settingsRepository);

        $this->supportAuthenticator = $supportAuthenticator;
        $this->ticketRepository = $ticketRepository;
    }

    /**
     * @throws AbortException
     */
    public function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub
        $user = $this->supportAuthenticator->getUser();
        if($user) {
            $helper = new \stdClass();
            $helper->authUser = $user;

            $this->template->helper = $helper;
            $this->user = $user;
        } else {
            $this->flashMessage('Před přístupem do helpdesku se musíš přihlásit a podstoupit ověření');
            $this->redirect('Login:main');
        }
    }

    /**
     * @param int $page
     */
    public function renderHome(int $page = 1) {
        $tickets = $this->ticketRepository->getAllTickets();
        $lastPage = 0;

        $paginatorData = $tickets->page($page, 6, $lastPage);

        $this->template->tickets = $paginatorData;
        $this->template->page = $page;
        $this->template->lastPage = $lastPage;

        if($lastPage === 0) {
            $this->template->page = 0;
        }
    }

    /**
     * @param $id
     */
    public function renderTicket($id) {
        $ticket = $this->ticketRepository->getTicketById($id);
        $this->template->ticket = $ticket;
        $this->template->ticketResponses = $this->ticketRepository->getTicketResponses($id);
        $this->template->responseTypes = $this->ticketRepository::TYPES;
        $captcha = Captcha::getRandomMethod();
        $this->template->captcha = $captcha;
        $this->template->captchaOrder = Captcha::getMethodOrder($captcha);
    }

    /**
     * @param $ticketId
     * @throws AbortException
     */
    public function actionDeleteTicket($ticketId) {
        $deleted = $this->ticketRepository->removeTicket($ticketId);
        if($deleted) {
            $this->flashMessage("Ticket " . $ticketId . " byl úspěšně odstraněn.", "success");
        } else {
            $this->flashMessage("Ticket nemohl být odstraněn, jelikož neexistuje.", "danger");
        }

        $this->redirect("Main:home");
    }

    /**
     * @throws AbortException
     * @throws AuthException
     */
    public function actionLogout() {
        $this->supportAuthenticator->logout();
        $this->flashMessage('Byl jsi odhlášen, pro další manipulaci s administrací se přihlaš!', 'success');
        $this->redirect('Login:main');
    }

    /**
     * @return Multiplier
     */
    public function createComponentAddResponseForm(): Multiplier {
        return new Multiplier(function ($methodOrder) { // captcha
            return new Multiplier(function ($ticketId) use ($methodOrder) { // ticket
                return (new AddResponseForm($this,
                    new Captcha(array_keys(Captcha::methods)[$methodOrder]), $this->ticketRepository, $this->user, $ticketId, TicketRepository::TYPES['support']))
                    ->create();
            });
        });
    }

    /**
     * @return Multiplier
     */
    public function createComponentCloseTicketForm(): Multiplier {
        return new Multiplier(function ($ticketId) {
            return (new CloseTicketForm($this, $this->ticketRepository, $ticketId))->create();
        });
    }

    /**
     * @return Multiplier
     */
    public function createComponentOpenTicketForm(): Multiplier {
        return new Multiplier(function ($ticketId) {
            return (new OpenTicketForm($this, $this->ticketRepository, $ticketId))->create();
        });
    }
}